# config/_default/languages.en.toml

languageCode = "en"
languageName = "English"

title = "Guanran928's blog."
copyright = "© 2024 Guanran928, licensed under [CC-BY-SA-4.0](https://creativecommons.org/licenses/by-sa/4.0/)"

[params.author]
name = "Guanran928"
image = "img/author.jpg"
links = [
  { github = "https://github.com/Guanran928" },
  { mastodon = "https://mastodon.ny4.dev/@nyancat" },
]
