# config/_default/languages.en.toml

languageCode = "en"
languageName = "English"

title = "Guanran928's blog."

[author]
name = "Guanran928"
image = "img/author.jpg"
headline = "This is me, probably."
bio = "Not a developer."
links = [{ github = "https://github.com/Guanran928" }]
