# config/_default/languages.en.toml

languageCode = "en"
languageName = "English"

title = "Guanran928's blog."

[params.author]
name = "Guanran928"
image = "img/author.jpg"
links = [
  { github = "https://github.com/Guanran928" },
  { mastodon = "https://mastodon.ny4.dev/@nyancat" },
]
