# config/_default/languages.zh-cn.toml

languageCode = "zh-cn"
languageName = "简体中文"

title = "Guanran928 的博客。"

[params.author]
name = "Guanran928"
image = "img/author.jpg"
links = [
  { github = "https://github.com/Guanran928" },
  { mastodon = "https://mastodon.ny4.dev/@nyancat" },
]
