# config/_default/menus.zh-cn.toml

[[main]]
name = "友链"
pageRef = "friends"
weight = 10

[[main]]
name = "服务"
pageRef = "services"
weight = 20

[[main]]
name = "文章"
pageRef = "posts"
weight = 30

[[main]]
name = "标签"
pageRef = "tags"
weight = 40

[[main]]
name = "GitHub"
url = "https://github.com/Guanran928/Guanran928.github.io"
weight = 50

[main.params]
icon = "github"
showName = false
target = "_blank"

[[main]]
identifier = "search"
weight = 99
[main.params]
action = "search"
icon = "search"
