# config/_default/params.toml

colorScheme = "ocean"
enableSearch = true
enableCodeCopy = true

[homepage]
layout = "profile"

[header]
layout = "hybrid"

[article]
showBreadcrumbs = true
showTableOfContents = true
showWordCount = true

[list]
showBreadcrumbs = true
showTableOfContents = true
showTaxonomies = true
